version: '3.3'
volumes:
  static:
  pg_data:
services:
  db:
    image: postgres:13.10
    environment:
      POSTGRES_DB: "django"
      POSTGRES_USER: "django_user"
      POSTGRES_PASSWORD: "mysecretpassword"
    ports:
      - "5432:5432"